#Build Settings
markdown: kramdown
title: My Portfolio
description: A showcase of my work
url: "https://SylviaMartin1.github.io"
remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme

